version: '3'
services:
  fssk-server:
        build:
          context: ./
          dockerfile: deploy/prod.docker
        hostname: 'server'
        container_name: 'fssk-server'
        env_file: ./server/.env
        environment:
          - 'NODE_ENV=production'
        command: ["./util/wait-for-it.sh", "npm", "run", "start:prod"]
        ports:
          - '4000:4000'
        working_dir: '/opt/server'
        depends_on:
          - fssk-db
        networks:
          - app
        volumes:
          - 'fssk-server-data:/opt/server/logs'
  fssk-db:
      environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=admin'
      image: 'postgres:9.6'
      ports:
        - '5432:5432'
      volumes:
        - 'fssk-db-data:/var/lib/mysql'
        - './db:/docker-entrypoint-initdb.d/'
      networks:
        app:
          aliases:
            - db
networks:
  app:
    driver: bridge

volumes:
  fssk-db-data:
  fssk-server-data:
