version: '2'
services:
  postgres:
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DATABASE=test
      - POSTGRES_PASSWORD=admin
    image: 'postgres:latest'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - './util/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh'
