version: '2'
services:
  fssk-node-client:
      build:
        context: ./
        dockerfile: deploy/client.docker
      hostname: 'client'
      container_name: 'fssk-node-client'
      env_file: ./client/.env
      command: 'npm start'
      ports:
        - '3000:3000'
      volumes:
        - './client:/opt/src'
      working_dir: '/opt/src'
      depends_on:
        - fssk-node-server
      links:
      - 'fssk-node-server:fssk-server'
      networks:
        - app
  fssk-node-server:
      build:
        context: ./
        dockerfile: deploy/server.docker
      hostname: 'server'
      container_name: 'fssk-node-server'
      env_file: ./server/.env
      command: 'npm start'
      ports:
        - '4000:4000'
      volumes:
        - './server:/opt/src'
      working_dir: '/opt/src'
      depends_on:
        - fssk-node-db
      links:
        - 'fssk-node-db:db'
      networks:
        - app
  fssk-node-db:
    environment:
    - 'POSTGRES_USER=root'
    - 'POSTGRES_DB=test'
    - 'POSTGRES_PASSWORD=admin'
    image: 'postgres:9.6'
    container_name: 'fssk-node-db'
    ports:
      - '5432:5432'
    volumes:
      - 'fssk-node-db-data:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d/'
    networks:
      - app
networks:
  app:
    driver: bridge
volumes:
  fssk-node-db-data:
  fssk-node-server-data:
