version: '2'
services:
  postgres:
    env_file: server/.env
    image: 'postgres:latest'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - './util/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh'
