version: 2
jobs:
  test_client:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/fssk-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
      - run:
          name: npm-install
          working_directory: ./client
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - ./client/node_modules
      - run:
          name: lint
          working_directory: ./client
          command: npm run lint
      - run:
          name: test
          working_directory: ./client
          command: npm run test:ci
      - store_test_results:
          path: ./client/build/spec
  build_client:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/fssk-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
      - run:
          name: npm-install
          working_directory: ./client
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - ./client/node_modules
      - run:
          name: build
          working_directory: ./client
          command: npm run build
  test_server:
    docker:
      - image: circleci/node:8.11.2
        environment:
        - DBHOST=localhost
        - PGUSER=ubuntu
        - DBNAME=circle_test
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=circle_test
    working_directory: ~/fssk-node
    steps:
      - checkout
      - run:
          name: Install postgres client
          command: sudo apt-get update && sudo apt-get install postgresql-client -y
      - restore_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
      - run:
          name: npm-install
          working_directory: ./server
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "server/package.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: lint
          working_directory: ./server
          command: npm run lint
      - run:
          name: test
          working_directory: ./server
          command: npm run test:ci
      - store_test_results:
          path: ./server/build/spec
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_client
      - build_client
      - test_server
