#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE "$POSTGRES_DATABASE";
    \c $POSTGRES_DATABASE
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL
